### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by oliverbarnes** [liquidvotingio/liquid-decidim-demo#10]
On updates to the decidim-module-liquidvoting gem

**Comment by oliverbarnes** [comment]
Update: got the demo dockerized (on #18) and manually deployed to our cluster by applying new manifests on https://github.com/liquidvotingio/deployment/pull/79. Have yet to work out migrations, which is WIP. I'll tackle the continuous deployment here on the CI.

The app is up on https://decidim-demo.liquidvoting.io/, but I haven't created the system user nor the organization yet.

**Comment by oliverbarnes** [comment]
Latest update:
- CI now builds and deploys a new image fetching our module from Github
- Sidekiq and Redis are now part of the deployment. Queues can be viewed at https://decidim-demo.liquidvoting.io/sidekiq by the admin user
- Migrations job manifest added, but isn't wired into the CI flow yet
- App is up and running and populated with an assembly and a proposal that can be found at https://decidim-demo.liquidvoting.io/assemblies/general-assembly/f/1/proposals/1, but which is barfing due to `api_state` being nil:

```bash
I, [2021-05-21T20:00:48.548952 #1] INFO -- : [10d53bc57eb795aae731b55d1e2a089d] Rendered cell decidim/progress_bar (4.1ms)
I, [2021-05-21T20:00:48.549555 #1] INFO -- : [10d53bc57eb795aae731b55d1e2a089d] Rendered /usr/local/bundle/bundler/gems/decidim-module-liquidvoting-ecd7207e571bviews/decidim/proposals/proposals/_votes_count.html.erb (12.1ms)
I, [2021-05-21T20:00:48.558681 #1] INFO -- : [10d53bc57eb795aae731b55d1e2a089d] Rendered /usr/local/bundle/bundler/gems/decidim-module-liquidvoting-ecd7207e571bviews/decidim/proposals/proposals/_vote_button.html.erb (7.2ms)
I, [2021-05-21T20:00:48.559290 #1] INFO -- : [10d53bc57eb795aae731b55d1e2a089d] Rendered /usr/local/bundle/bundler/gems/decidim-module-liquidvoting-ecd7207e571bviews/decidim/proposals/proposals/show.html.erb within layouts/decidim/assembly (636.6ms)
I, [2021-05-21T20:00:48.562407 #1] INFO -- : [10d53bc57eb795aae731b55d1e2a089d] Completed 500 Internal Server Error in 1430ms (ActiveRecord: 260.9ms)
F, [2021-05-21T20:00:48.566225 #1] FATAL -- : [10d53bc57eb795aae731b55d1e2a089d]
F, [2021-05-21T20:00:48.566647 #1] FATAL -- : [10d53bc57eb795aae731b55d1e2a089d] ActionView::Template::Error (undefined method `delegate_id' for nil:NilClass):
F, [2021-05-21T20:00:48.567127 #1] FATAL -- : [10d53bc57eb795aae731b55d1e2a089d] 14: <span class="show-for-sr"><%= decidim_html_escape(present(proposal).title) %></span>
[10d53bc57eb795aae731b55d1e2a089d] 15: <% end %>
[10d53bc57eb795aae731b55d1e2a089d] 16: <% end %>
[10d53bc57eb795aae731b55d1e2a089d] 17: <% elsif api_state.delegate_id %>
[10d53bc57eb795aae731b55d1e2a089d] 18: <%= content_tag :button, t("decidim.proposals.proposals.vote_button.vote_delegated"), class: "button #{vote_button_classes(from_proposals_list)} disabled", id: "vote_button-#{proposal.id}", disabled: true %>
[10d53bc57eb795aae731b55d1e2a089d] 19: <% else %>
[10d53bc57eb795aae731b55d1e2a089d] 20: <% if api_state.user_has_supported %>
F, [2021-05-21T20:00:48.567426 #1] FATAL -- : [10d53bc57eb795aae731b55d1e2a089d]
F, [2021-05-21T20:00:48.567734 #1] FATAL -- : [10d53bc57eb795aae731b55d1e2a089d] /usr/local/bundle/bundler/gems/decidim-module-liquidvoting-ecd7207e571bviews/decidim/proposals/proposals/_vote_button.html.erb:17:in `__usr_local_bundle_bundler_gems_decidim_module_liquidvoting_ecd____e___bviews_decidim_proposals_proposals__vote_button_html_erb___989429553512459827_277880'
[10d53bc57eb795aae731b55d1e2a089d] actionview (5.2.4.5) lib/action_view/template.rb:159:in `block in render'
[10d53bc57eb795aae731b55d1e2a089d] activesupport (5.2.4.5) lib/active_support/notifications.rb:170:in `instrument'
[10d53bc57eb795aae731b55d1e2a089d] actionview (5.2.4.5) lib/action_view/template.rb:354:in `instrument_render_template'
[10d53bc57eb795aae731b55d1e2a089d] actionview (5.2.4.5) lib/action_view/template.rb:157:in `render'
[10d53bc57eb795aae731b55d1e2a089d] actionview (5.2.4.5) lib/action_view/renderer/partial_renderer.rb:344:in `block in render_partial'
```

**Comment by oliverbarnes** [comment]
Demo deployment pods also seem to be going into crash loops and restarting from time to time, but after a while stabilize. Wondering if it's a swap issue the Platoniq people warned about in one of their guides, or whether it's simply not connecting to our api yet. Will continue investigating

**Comment by oliverbarnes** [comment]
api_state issue fixed, the proposal is now visible at https://decidim-demo.liquidvoting.io/assemblies/general-assembly/f/1/proposals/1 and a user is able to both support and delegate.

sidekiq deployment is still shaky, going into pod errors which destabilize other deployments.

**Comment by oliverbarnes** [comment]
sidekiq deployment now stable after resizing the cluster, one of the nodes there was starving for memory. 

Email confirmation of signup still doesn't get sent through gmail, though - fails with `Net::OpenTimeout: execution expired`. Will look into this next

**Comment by oliverbarnes** [comment]
Confirmation emails finally coming through now with Sendgrid. Still no idea why it wouldn't work with Mailjet. Closing this as the demo is now deployed and up and running, and test-driven somewhat
